#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

# All settings may be overriden in wagons!

application:
  name: hitobito  # set same name in email.sender and email.mass_recipient
  footer:
    #logo_image: logo_hitobito.png
    logo_url: http://puzzle.ch
    links: {}

  # The languages available in the menu
  languages:
    de: Deutsch

<% mail_domain = ENV['RAILS_MAIL_DOMAIN'].presence ||
                 ENV['RAILS_HOST_NAME'].presence ||
                 'localhost' %>

email:
  # Sender for all emails sent by the application
  sender: <%= "hitobito <noreply@#{mail_domain}>" %>

  # If mass emails are sent, this recipient is used in the to field,
  # while the actual recipients go in the bcc field.
  mass_recipient: <%= "hitobito <noreply@#{mail_domain}>" %>

  # domain where mailing lists are located
  list_domain: <%= mail_domain %>

  # configuration for retrieving email
  retriever:
    # interval to check for new mails in minutes
    interval: 1
    type: <%= ENV['RAILS_MAIL_RETRIEVER_TYPE'].presence || 'pop3' %>
    config:
      <% if ENV['RAILS_MAIL_RETRIEVER_CONFIG'].present? %>
        <%= "{ #{ENV['RAILS_MAIL_RETRIEVER_CONFIG']} }" %>
      <% else %>
        address:    <%= ENV['RAILS_MAIL_RETRIEVER_ADDRESS'] %>
        port:       <%= ENV['RAILS_MAIL_RETRIEVER_PORT'].presence || 995 %>
        user_name:  <%= ENV['RAILS_MAIL_RETRIEVER_USER'] %>
        password:   <%= ENV['RAILS_MAIL_RETRIEVER_PASSWORD'] %>
        enable_ssl: <%= %w(true yes 1).include?(ENV['RAILS_MAIL_RETRIEVER_SSL']) %>
      <% end %>

# The person with this email has root access to everything
# This person should only be used by the operators of the application, not the customers.
# Initially, a password reset token may be mailed from the application to this address to set a password.
root_email: hitobito@puzzle.ch


phone_number:
  predefined_labels:
    - Privat
    - Mobil
    - Arbeit
    - Vater
    - Mutter
    - Fax
    - Andere

social_account:
  predefined_labels:
    - Facebook
    - MSN
    - Skype
    - Twitter
    - Webseite
    - Andere

additional_email:
  predefined_labels:
    - Privat
    - Arbeit
    - Vater
    - Mutter
    - Andere

# Presets for PDF labels
pdf:
  labels:
    # Minimum border on the right and bottom of each label
    min_border: 4 #mm
    font_name: Helvetica

# Preset for addresses
address:
  ignored_countries:
    - ch
    - schweiz

# Presets for CSV export
csv:
  # optimized for M$ Excel
  separator: ;
  encoding: ISO-8859-1

role:
  # If a role last less than this number of days, it is not archived
  minimum_days_to_archive: 7
